const DEALER_VALUATION_COLLECTION = "dealer_valuation";
const DEALER_VALUATION_SINGLETON_KEY = "default";
const DEALER_OPENING_VALUATION_BDT = 2000000;

module.exports = {
    DEALER_VALUATION_COLLECTION,
    DEALER_VALUATION_SINGLETON_KEY,
    DEALER_OPENING_VALUATION_BDT,
};
